# Generated by Django 5.2.3 on 2025-06-24 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.PositiveIntegerField()),
                ('especie', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='pets/')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('banho', 'Banho'), ('vacina', 'Vacina'), ('consulta', 'Consulta'), ('remedio', 'Remédio')], max_length=20)),
                ('data', models.DateField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='agenda.pet')),
            ],
        ),
    ]
