# Generated by Django 5.2.2 on 2025-06-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_evento_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
